import { Product } from "../ProductCard";

// Имитация данных каталога
export const catalogProducts: Product[] = [
  {
    id: "1",
    name: "Кольцо Infinity",
    price: 12500,
    category: "Кольца",
    materials: ["Серебро 925", "Керамика"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isBestseller: true,
  },
  {
    id: "2",
    name: "Серьги Minimal",
    price: 9800,
    category: "Серьги",
    materials: ["Серебро 925"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isBestseller: true,
  },
  {
    id: "3",
    name: "Браслет Connection",
    price: 15700,
    category: "Браслеты",
    materials: ["Серебро 925", "Кожа"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isBestseller: true,
  },
  {
    id: "4",
    name: "Колье Horizon",
    price: 18900,
    category: "Колье",
    materials: ["Золото 585", "Бриллиант"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isBestseller: true,
  },
  {
    id: "5",
    name: "Кольцо Twist",
    price: 14200,
    category: "Кольца",
    materials: ["Серебро 925", "Цирконий"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isNew: true,
  },
  {
    id: "6",
    name: "Серьги Cascade",
    price: 11500,
    category: "Серьги",
    materials: ["Серебро 925"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isNew: true,
  },
  {
    id: "7",
    name: "Подвеска Urban",
    price: 10500,
    category: "Подвески",
    materials: ["Серебро 925", "Оникс"],
    images: ["/placeholder.svg", "/placeholder.svg"],
    isNew: true,
  },
  {
    id: "8",
    name: "Браслет Geometry",
    price: 13800,
    category: "Браслеты",
    materials: ["Золото 585"],
    images: ["/placeholder.svg", "/placeholder.svg"],
  },
  {
    id: "9",
    name: "Кольцо Eclipse",
    price: 16500,
    category: "Кольца",
    materials: ["Серебро 925", "Черный жемчуг"],
    images: ["/placeholder.svg", "/placeholder.svg"],
  },
];